/*
 * PowerGeneratorGUI.java
 *
 * Created on 03 Mayıs 2007 Perşembe, 19:50
 */

package com.evo.de.GUI;

import javax.swing.JOptionPane;
/**
 *
 * @author  root
 */
public class DemandGUI extends javax.swing.JPanel {
    
    private int index;
    
    private DemandGUI() {
        initComponents();
    }
    /** Creates new form PowerGeneratorGUI */
    public DemandGUI( final int index)
    {
        this();
        this.index = index;
        this.hour_label.setText( (index + 1) + ". hour" );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        demand = new javax.swing.JTextField();
        reserve = new javax.swing.JTextField();
        hour_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Demand");

        jLabel2.setText("Reserve");

        demand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                demandFocusLost(evt);
            }
        });

        reserve.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reserveFocusLost(evt);
            }
        });

        hour_label.setText("jLabel3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(hour_label)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(reserve)
                            .add(demand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(hour_label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(demand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(reserve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reserveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reserveFocusLost
        try{
            PowerGeneratorGUI.convertDouble(this.demand);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_reserveFocusLost

    private void demandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_demandFocusLost
        try{
            PowerGeneratorGUI.convertDouble(this.reserve);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_demandFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField demand;
    private javax.swing.JLabel hour_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField reserve;
    // End of variables declaration//GEN-END:variables
    
}
