/*
 * DemandGUI.java
 *
 * Created on 03 Mayıs 2007 Perşembe, 19:50
 */

package com.evo.de.GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author  root
 */
public class PowerGeneratorGUI extends javax.swing.JPanel {
    
    private int index;
    
    /** Creates new form DemandGUI */
    private PowerGeneratorGUI() {
        initComponents();
    }
    
    public PowerGeneratorGUI( final int index) {
        this();
        this.index = index;
        this.generator_label.setText( (index + 1) + ". unit" );
    }
    
    public static double convertDouble( JTextField field ) throws NumberFormatException, Exception{
        
        double intValue = 0;
        String value = field.getText();
        if( !value.equals("") ){
        try{
            intValue = Double.valueOf( value );
        } catch(NumberFormatException e){
            field.setBackground( Color.RED );
            throw e;
        }
        
        
        field.setBackground( Color.WHITE );
        }
        
        return intValue;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Pmax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cost_a = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cost_b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cost_c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_up = new javax.swing.JTextField();
        t_down = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hot_start = new javax.swing.JTextField();
        cold_start = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_cold_start = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        initial_state = new javax.swing.JTextField();
        generator_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        Pmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PmaxFocusLost(evt);
            }
        });

        jLabel1.setText("Pmax (MW)");

        jLabel2.setText("Pmin (MW)");

        Pmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PminFocusLost(evt);
            }
        });

        jLabel3.setText("a");

        cost_a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cost_aFocusLost(evt);
            }
        });

        jLabel4.setText("b");

        cost_b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cost_bFocusLost(evt);
            }
        });

        jLabel5.setText("c");

        cost_c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cost_cFocusLost(evt);
            }
        });

        jLabel6.setText("t_up (h)");

        jLabel7.setText("t_down (h)");

        t_up.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_upFocusLost(evt);
            }
        });

        t_down.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_downFocusLost(evt);
            }
        });

        jLabel8.setText("Hot start ($)");

        jLabel9.setText("Cold start ($)");

        hot_start.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hot_startFocusLost(evt);
            }
        });

        cold_start.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cold_startFocusLost(evt);
            }
        });

        jLabel10.setText("t_cold_start (h)");

        t_cold_start.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cold_startFocusLost(evt);
            }
        });

        jLabel11.setText("Initial State (h)");

        initial_state.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                initial_stateFocusLost(evt);
            }
        });

        generator_label.setText("jLabel12");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(generator_label)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(Pmax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(t_down, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(hot_start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Pmin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(layout.createSequentialGroup()
                                .add(65, 65, 65)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(cold_start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel10))
                            .add(layout.createSequentialGroup()
                                .add(cost_a, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel4)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(t_cold_start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(initial_state, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(cost_b, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cost_c, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(25, 25, 25)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(t_up, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(generator_label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(Pmax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Pmin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(t_down, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8)
                            .add(hot_start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(1, 1, 1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cost_a, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3)
                            .add(cost_b, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4)
                            .add(t_up, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cost_c, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cold_start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t_cold_start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(initial_state, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9)
                            .add(jLabel11)
                            .add(jLabel10))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void initial_stateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_initial_stateFocusLost
        
        try{
            convertDouble(this.initial_state);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_initial_stateFocusLost
    
    private void t_cold_startFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cold_startFocusLost
        
        
        try{
            convertDouble(this.t_cold_start);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_t_cold_startFocusLost
    
    private void cold_startFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cold_startFocusLost
        
        try{
            convertDouble(this.cold_start);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_cold_startFocusLost
    
    private void hot_startFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hot_startFocusLost
        
        try{
            convertDouble(this.hot_start);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_hot_startFocusLost
    
    private void t_downFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_downFocusLost
        try{
            convertDouble(this.t_down);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_t_downFocusLost
    
    private void t_upFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_upFocusLost
        
        try{
            convertDouble(this.t_up);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_t_upFocusLost
    
    private void cost_cFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cost_cFocusLost
        
        try{
            convertDouble(this.cost_c);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_cost_cFocusLost
    
    private void cost_bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cost_bFocusLost
        
        try{
            convertDouble(this.cost_b);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_cost_bFocusLost
    
    private void cost_aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cost_aFocusLost
        
        try{
            convertDouble(this.cost_a);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_cost_aFocusLost
    
    private void PminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PminFocusLost
        
        try{
            convertDouble(this.Pmin);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_PminFocusLost
    
    private void PmaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PmaxFocusLost
        try{
            convertDouble(this.Pmax);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You should enter a valid value");
        } catch(Exception e2){
            
        }
    }//GEN-LAST:event_PmaxFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Pmax;
    public javax.swing.JTextField Pmin;
    public javax.swing.JTextField cold_start;
    public javax.swing.JTextField cost_a;
    public javax.swing.JTextField cost_b;
    public javax.swing.JTextField cost_c;
    private javax.swing.JLabel generator_label;
    public javax.swing.JTextField hot_start;
    public javax.swing.JTextField initial_state;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField t_cold_start;
    public javax.swing.JTextField t_down;
    public javax.swing.JTextField t_up;
    // End of variables declaration//GEN-END:variables
    
}
